/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiderRouteImport } from './routes/rider'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ApiPublicGroupOrdersTickRouteImport } from './routes/api/public/group-orders/tick'

const RiderRoute = RiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGroupOrdersTickRoute =
  ApiPublicGroupOrdersTickRouteImport.update({
    id: '/api/public/group-orders/tick',
    path: '/api/public/group-orders/tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/restaurant': typeof RestaurantRoute
  '/rider': typeof RiderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/public/group-orders/tick': typeof ApiPublicGroupOrdersTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/restaurant': typeof RestaurantRoute
  '/rider': typeof RiderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/orders': typeof OrdersIndexRoute
  '/api/public/group-orders/tick': typeof ApiPublicGroupOrdersTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/restaurant': typeof RestaurantRoute
  '/rider': typeof RiderRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/public/group-orders/tick': typeof ApiPublicGroupOrdersTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/notifications'
    | '/profile'
    | '/restaurant'
    | '/rider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/orders/'
    | '/api/public/group-orders/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/notifications'
    | '/profile'
    | '/restaurant'
    | '/rider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/orders'
    | '/api/public/group-orders/tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/notifications'
    | '/profile'
    | '/restaurant'
    | '/rider'
    | '/orders/$id'
    | '/restaurants/$id'
    | '/orders/'
    | '/api/public/group-orders/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RestaurantRoute: typeof RestaurantRoute
  RiderRoute: typeof RiderRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ApiPublicGroupOrdersTickRoute: typeof ApiPublicGroupOrdersTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rider': {
      id: '/rider'
      path: '/rider'
      fullPath: '/rider'
      preLoaderRoute: typeof RiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/group-orders/tick': {
      id: '/api/public/group-orders/tick'
      path: '/api/public/group-orders/tick'
      fullPath: '/api/public/group-orders/tick'
      preLoaderRoute: typeof ApiPublicGroupOrdersTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RestaurantRoute: RestaurantRoute,
  RiderRoute: RiderRoute,
  OrdersIdRoute: OrdersIdRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ApiPublicGroupOrdersTickRoute: ApiPublicGroupOrdersTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
